### ISSUE TITLE
Which repository is right?

### ISSUE THREAD

**Issue by rjahn** [kee-org/flutter_treeview#1]
Which repository is the right one?

https://bitbucket.org/kevinandre/flutter_treeview/src/master/
or
https://github.com/kee-org/flutter_treeview

**Comment by luckyrat** [comment]
This is the repo which fixes problems that prevented the pub hosted version from working for some years now. I've not needed to make changes for most recent Flutter versions but have yet to try 3.27.

Use this repo something like this in pubspec.yaml:
```
  flutter_treeview:
    git:
      url: https://github.com/kee-org/flutter_treeview.git
      ref: 41356d7a7887cae938f4913f4534e7217387ec0b
```
